name: Delete Branch on Issue Close

on:
  issues:
    types: [closed]

jobs:
  delete-branch:
    runs-on: ubuntu-latest

    steps:
      # Extract branch name from the issue body
      - name: Extract branch name from issue
        id: extract-branch
        run: |
          echo "Issue Body:"
          echo "${{ github.event.issue.body }}"
          
          # Extract the branch name from the issue body
          BRANCH_NAME=$(echo "${{ github.event.issue.body }}" | grep -oP '(?<=🌳 브랜치명 \(Branch\): ).*')
          
          if [ -z "$BRANCH_NAME" ]; then
            echo "Branch name is missing in the issue body. Exiting."
            exit 1
          fi
          
          echo "Branch Name: $BRANCH_NAME"
          echo "::set-output name=branch::$BRANCH_NAME"

      # Delete the branch using GitHub API
      - name: Delete branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME="${{ steps.extract-branch.outputs.branch }}"
          
          # Call GitHub API to delete the branch
          curl -X DELETE \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/git/refs/heads/$BRANCH_NAME || echo "Branch already deleted or does not exist."
