name: Delete Branch on Issue Close

on:
  issues:
    types: [closed]

jobs:
  delete-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Get linked branches
        id: get-branches
        run: |
          branches=$(gh api /repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/branches | jq -r '.[].name')
          echo "branches=$branches" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete branches
        if: ${{ steps.get-branches.outputs.branches != '' }}
        run: |
          for branch in ${{ steps.get-branches.outputs.branches }}; do
            gh api -X DELETE /repos/${{ github.repository }}/git/refs/heads/$branch
            echo "Deleted branch: $branch"
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
